### ISSUE TITLE
叮咚买菜这个好像不行，如果预约时间都已约满会报bug

### ISSUE THREAD

**Issue by Kevenyf** [AoperX/qiangcai#1]

**Comment by cto-williamsong** [comment]
已修复,添加对应判断代码

**Comment by Kevenyf** [comment]
楼主你更新后的这个代码对于比如只是某个时间段已约满的情况也会出bug，看你代码逻辑无论有无时间段可以送菜，总是会点击最后一个时间段，点击完后对于没有抢到的情况不会一直监控直到抢到

**Comment by cto-williamsong** [comment]
对的, 绕过高峰期,还没想到更好的方法. 如果有更好的方法,欢迎push
