### ISSUE TITLE
希望能加个捡漏模式

### ISSUE THREAD

**Issue by liuyuan1114** [AoperX/qiangcai#2]
高峰时期美团买菜几乎不能抢到，我看很多人捡漏能抢到。这个代码一运行到没货或者时间预约满 就停了，要是能支持捡漏就好了。

**Comment by cto-williamsong** [comment]
嗯...这个插件基于python自动化测试实现.捡漏模式的实现原理有两种: 1. 需要不断刷新手机,获取数据,2.调用美团接口查询(涉嫌安全方面问题); 所以捡漏模式建议使用其他大佬采用接口方式实现的插件.谢谢你的issue;
